/*
 * Created on 2023-07-13 ( 10:15:52 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
/**
 * JPA entity class for "Appointment"
 */

package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name="appointment", catalog="tap" )
public class Appointment implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private long id;

    @Column(name="start")
	private LocalDateTime start;

    @Column(name="end")
	private LocalDateTime end;

    @Column(name="created_date", nullable=false)
	private LocalDateTime createdDate;

    @Column(name="status_response_date")
	private LocalDateTime statusResponseDate;

    @Column(name="comment", length=512)
	private String comment;


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="appointment_status_id", referencedColumnName="id")
	private AppointmentStatus appointmentstatus ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="appointment_type_id", referencedColumnName="id")
	private AppointmentType appointmenttype ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="employee_id", referencedColumnName="id")
	private Employee employee ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="provider_service_id", referencedColumnName="id")
	private Service service ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="repeat_type_id", referencedColumnName="id")
	private RepeatType repeattype ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="user_id", referencedColumnName="id")
	private User user ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="created_by_id", referencedColumnName="id")
	private User user2 ; 

	public Appointment() {
		super();
	}
	
	public void setId( long id ) {
		this.id = id ;
	}

	public long getId() {
		return this.id;
	}

	public void setStart( LocalDateTime start ) {
		this.start = start ;
	}

	public LocalDateTime getStart() {
		return this.start;
	}

	public void setEnd( LocalDateTime end ) {
		this.end = end ;
	}

	public LocalDateTime getEnd() {
		return this.end;
	}

	public void setCreatedDate( LocalDateTime createdDate ) {
		this.createdDate = createdDate ;
	}

	public LocalDateTime getCreatedDate() {
		return this.createdDate;
	}

	public void setStatusResponseDate( LocalDateTime statusResponseDate ) {
		this.statusResponseDate = statusResponseDate ;
	}

	public LocalDateTime getStatusResponseDate() {
		return this.statusResponseDate;
	}

	public void setComment( String comment ) {
		this.comment = comment ;
	}

	public String getComment() {
		return this.comment;
	}

	public AppointmentStatus getAppointmentstatus() {
		return this.appointmentstatus;
	}
	
	public void setAppointmentstatus(AppointmentStatus appointmentstatus) {
		this.appointmentstatus = appointmentstatus;
	}
	public AppointmentType getAppointmenttype() {
		return this.appointmenttype;
	}
	
	public void setAppointmenttype(AppointmentType appointmenttype) {
		this.appointmenttype = appointmenttype;
	}
	public Employee getEmployee() {
		return this.employee;
	}
	
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}
	public Service getService() {
		return this.service;
	}
	
	public void setService(Service service) {
		this.service = service;
	}
	public RepeatType getRepeattype() {
		return this.repeattype;
	}
	
	public void setRepeattype(RepeatType repeattype) {
		this.repeattype = repeattype;
	}
	public User getUser() {
		return this.user;
	}
	
	public void setUser(User user) {
		this.user = user;
	}
	public User getUser2() {
		return this.user2;
	}
	
	public void setUser2(User user2) {
		this.user2 = user2;
	}
}