/*
 * Created on 2023-08-01 ( 15:55:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
/**
 * JPA entity class for "BusyPeriod"
 */

package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

@Entity
@Table(name="busy_period", catalog="tap" )
public class BusyPeriod implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private long id;

    @Column(name="start_date")
	private LocalDate startDate;

    @Column(name="start_time")
	private LocalTime startTime;

    @Column(name="end_date")
	private LocalDate endDate;

    @Column(name="end_time")
	private LocalTime endTime;

    @Column(name="comment", length=65535)
	private String comment;

    @Column(name="create_date", nullable=false)
	private LocalDateTime createDate;


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="period_type_id", referencedColumnName="id")
	private PeriodType periodtype ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="provider_id", referencedColumnName="id")
	private Provider provider ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="repeat_type_id", referencedColumnName="id")
	private RepeatType repeattype ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="created_by", referencedColumnName="id")
	private User user ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="used_by", referencedColumnName="id")
	private User user2 ; 

	public BusyPeriod() {
		super();
	}
	
	public void setId( long id ) {
		this.id = id ;
	}

	public long getId() {
		return this.id;
	}

	public void setStartDate( LocalDate startDate ) {
		this.startDate = startDate ;
	}

	public LocalDate getStartDate() {
		return this.startDate;
	}

	public void setStartTime( LocalTime startTime ) {
		this.startTime = startTime ;
	}

	public LocalTime getStartTime() {
		return this.startTime;
	}

	public void setEndDate( LocalDate endDate ) {
		this.endDate = endDate ;
	}

	public LocalDate getEndDate() {
		return this.endDate;
	}

	public void setEndTime( LocalTime endTime ) {
		this.endTime = endTime ;
	}

	public LocalTime getEndTime() {
		return this.endTime;
	}

	public void setComment( String comment ) {
		this.comment = comment ;
	}

	public String getComment() {
		return this.comment;
	}

	public void setCreateDate( LocalDateTime createDate ) {
		this.createDate = createDate ;
	}

	public LocalDateTime getCreateDate() {
		return this.createDate;
	}

	public PeriodType getPeriodtype() {
		return this.periodtype;
	}
	
	public void setPeriodtype(PeriodType periodtype) {
		this.periodtype = periodtype;
	}
	public Provider getProvider() {
		return this.provider;
	}
	
	public void setProvider(Provider provider) {
		this.provider = provider;
	}
	public RepeatType getRepeattype() {
		return this.repeattype;
	}
	
	public void setRepeattype(RepeatType repeattype) {
		this.repeattype = repeattype;
	}
	public User getUser() {
		return this.user;
	}
	
	public void setUser(User user) {
		this.user = user;
	}
	public User getUser2() {
		return this.user2;
	}
	
	public void setUser2(User user2) {
		this.user2 = user2;
	}
}