/*
 * Created on 2023-06-20 ( 07:13:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;
import java.util.List;

/**
 * JPA entity class for "City"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="city", catalog="tap" )
public class City implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

	//--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private short id ;

	//--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=64)
	private String name ;

    @Column(name="post_code", nullable=false, length=16)
	private String postCode ;

    @Column(name="country_id", nullable=false)
	private short countryId ;

    @Column(name="active", nullable=false)
	private boolean active ;


	//--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="city")
	private List<Address> addressList ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="country_id", referencedColumnName="id", insertable=false, updatable=false)
	private Country    country ; 


	/**
	 * Constructor
	 */
	public City() {
		super();
	}
	
	//--- GETTERS & SETTERS FOR FIELDS
	public void setId( short id ) {
		this.id = id ;
	}
	public short getId() {
		return this.id;
	}

	public void setName( String name ) {
		this.name = name ;
	}
	public String getName() {
		return this.name;
	}

	public void setPostCode( String postCode ) {
		this.postCode = postCode ;
	}
	public String getPostCode() {
		return this.postCode;
	}

	public void setCountryId( short countryId ) {
		this.countryId = countryId ;
	}
	public short getCountryId() {
		return this.countryId;
	}

	public void setActive( boolean active ) {
		this.active = active ;
	}
	public boolean isActive() {
		return this.active;
	}

	//--- GETTERS FOR LINKS
	public List<Address> getAddressList() {
		return this.addressList;
	} 

	public Country getCountry() {
		return this.country;
	} 

	//--- toString specific method
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(postCode);
  sb.append("|");
  sb.append(countryId);
  sb.append("|");
  sb.append(active);
  return sb.toString(); 
 } 

}