/*
 * Created on 2023-06-20 ( 07:13:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;
import java.util.List;

/**
 * JPA entity class for "Country"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="country", catalog="tap" )
public class Country implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

	//--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private short id ;

	//--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=64)
	private String name ;

    @Column(name="code", nullable=false, length=2)
	private String code ;

    @Column(name="phone", nullable=false)
	private int phone ;

    @Column(name="currency", nullable=false, length=4)
	private String currency ;

    @Column(name="currency_symbol", nullable=false, length=16)
	private String currencySymbol ;

    @Column(name="active", nullable=false)
	private byte active ;


	//--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="country")
	private List<City> cityList ; 


	/**
	 * Constructor
	 */
	public Country() {
		super();
	}
	
	//--- GETTERS & SETTERS FOR FIELDS
	public void setId( short id ) {
		this.id = id ;
	}
	public short getId() {
		return this.id;
	}

	public void setName( String name ) {
		this.name = name ;
	}
	public String getName() {
		return this.name;
	}

	public void setCode( String code ) {
		this.code = code ;
	}
	public String getCode() {
		return this.code;
	}

	public void setPhone( int phone ) {
		this.phone = phone ;
	}
	public int getPhone() {
		return this.phone;
	}

	public void setCurrency( String currency ) {
		this.currency = currency ;
	}
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrencySymbol( String currencySymbol ) {
		this.currencySymbol = currencySymbol ;
	}
	public String getCurrencySymbol() {
		return this.currencySymbol;
	}

	public void setActive( byte active ) {
		this.active = active ;
	}
	public byte getActive() {
		return this.active;
	}

	//--- GETTERS FOR LINKS
	public List<City> getCityList() {
		return this.cityList;
	} 

	//--- toString specific method
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(code);
  sb.append("|");
  sb.append(phone);
  sb.append("|");
  sb.append(currency);
  sb.append("|");
  sb.append(currencySymbol);
  sb.append("|");
  sb.append(active);
  return sb.toString(); 
 } 

}