/*
 * Created on 2023-06-20 ( 07:13:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;
import java.util.List;

/**
 * JPA entity class for "Employee"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="employee", catalog="tap" )
public class Employee implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

	//--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private int id ;

	//--- ENTITY DATA FIELDS 
    @Column(name="provider_id", nullable=false)
	private int providerId ;

    @Column(name="user_id", nullable=false)
	private int userId ;


	//--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="employee")
	private List<Appointment> appointmentList ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="provider_id", referencedColumnName="id", insertable=false, updatable=false)
	private Provider   provider ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
	private User       user ; 

    @OneToMany(mappedBy="employee")
	private List<EmployeeWorkPeriod> employeeworkperiodList ; 

    @OneToMany(mappedBy="employee")
	private List<ServiceEmployee> serviceemployeeList ; 


	/**
	 * Constructor
	 */
	public Employee() {
		super();
	}
	
	//--- GETTERS & SETTERS FOR FIELDS
	public void setId( int id ) {
		this.id = id ;
	}
	public int getId() {
		return this.id;
	}

	public void setProviderId( int providerId ) {
		this.providerId = providerId ;
	}
	public int getProviderId() {
		return this.providerId;
	}

	public void setUserId( int userId ) {
		this.userId = userId ;
	}
	public int getUserId() {
		return this.userId;
	}

	//--- GETTERS FOR LINKS
	public List<Appointment> getAppointmentList() {
		return this.appointmentList;
	} 

	public Provider getProvider() {
		return this.provider;
	} 

	public User getUser() {
		return this.user;
	} 

	public List<EmployeeWorkPeriod> getEmployeeworkperiodList() {
		return this.employeeworkperiodList;
	} 

	public List<ServiceEmployee> getServiceemployeeList() {
		return this.serviceemployeeList;
	} 

	//--- toString specific method
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(providerId);
  sb.append("|");
  sb.append(userId);
  return sb.toString(); 
 } 

}