/*
 * Created on 2023-06-20 ( 07:13:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;
import java.util.List;

/**
 * JPA entity class for "ProviderType"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="provider_type", catalog="tap" )
public class ProviderType implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

	//--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private short id ;

	//--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=64)
	private String name ;

    @Column(name="description", length=512)
	private String description ;

    @Column(name="active", nullable=false)
	private boolean active ;


	//--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="providertype")
	private List<Provider> providerList ; 


	/**
	 * Constructor
	 */
	public ProviderType() {
		super();
	}
	
	//--- GETTERS & SETTERS FOR FIELDS
	public void setId( short id ) {
		this.id = id ;
	}
	public short getId() {
		return this.id;
	}

	public void setName( String name ) {
		this.name = name ;
	}
	public String getName() {
		return this.name;
	}

	public void setDescription( String description ) {
		this.description = description ;
	}
	public String getDescription() {
		return this.description;
	}

	public void setActive( boolean active ) {
		this.active = active ;
	}
	public boolean isActive() {
		return this.active;
	}

	//--- GETTERS FOR LINKS
	public List<Provider> getProviderList() {
		return this.providerList;
	} 

	//--- toString specific method
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(description);
  sb.append("|");
  sb.append(active);
  return sb.toString(); 
 } 

}