/*
 * Created on 2023-06-20 ( 07:13:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;
import java.util.List;

/**
 * JPA entity class for "Role"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="role", catalog="tap" )
public class Role implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

	//--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private byte id ;

	//--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=64)
	private String name ;

    @Column(name="active", nullable=false)
	private byte active ;


	//--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="role")
	private List<UserRole> userroleList ; 


	/**
	 * Constructor
	 */
	public Role() {
		super();
	}
	
	//--- GETTERS & SETTERS FOR FIELDS
	public void setId( byte id ) {
		this.id = id ;
	}
	public byte getId() {
		return this.id;
	}

	public void setName( String name ) {
		this.name = name ;
	}
	public String getName() {
		return this.name;
	}

	public void setActive( byte active ) {
		this.active = active ;
	}
	public byte getActive() {
		return this.active;
	}

	//--- GETTERS FOR LINKS
	public List<UserRole> getUserroleList() {
		return this.userroleList;
	} 

	//--- toString specific method
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(name);
  sb.append("|");
  sb.append(active);
  return sb.toString(); 
 } 

}