/*
 * Created on 2023-07-13 ( 00:26:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
/**
 * JPA entity class for "ServiceEmployee"
 */

package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;

@Entity
@Table(name="service_employee", catalog="tap" )
public class ServiceEmployee implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private int id;


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="employee_id", referencedColumnName="id")
	private Employee employee ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="service_id", referencedColumnName="id")
	private Service service ; 

	public ServiceEmployee() {
		super();
	}
	
	public void setId( int id ) {
		this.id = id ;
	}

	public int getId() {
		return this.id;
	}

	public Employee getEmployee() {
		return this.employee;
	}
	public Service getService() {
		return this.service;
	}
}