/*
 * Created on 2023-07-14 ( 00:26:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
/**
 * JPA entity class for "Token"
 */

package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;

@Entity
@Table(name="token", catalog="tap" )
public class Token implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

    @Id
    @Column(name="id", nullable=false)
	private long id;

    @Column(name="token", length=128)
	private String token;


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="token_status_id", referencedColumnName="id")
	private TokenStatus tokenstatus ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="user_id", referencedColumnName="id")
	private User user ; 

	public Token() {
		super();
	}
	
	public void setId( long id ) {
		this.id = id ;
	}

	public long getId() {
		return this.id;
	}

	public void setToken( String token ) {
		this.token = token ;
	}

	public String getToken() {
		return this.token;
	}

	public TokenStatus getTokenstatus() {
		return this.tokenstatus;
	}
	
	public void setTokenstatus(TokenStatus tokenstatus) {
		this.tokenstatus = tokenstatus;
	}
	public User getUser() {
		return this.user;
	}
	
	public void setUser(User user) {
		this.user = user;
	}
}