/*
 * Created on 2023-06-20 ( 07:13:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package com.tap.db.entity;

import java.io.Serial;
import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "UserRole"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="user_role", catalog="tap" )
public class UserRole implements Serializable {
	@Serial
	private static final long serialVersionUID = 1L;

	//--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
	private int id ;

	//--- ENTITY DATA FIELDS 
    @Column(name="user_id", nullable=false)
	private int userId ;

    @Column(name="role_id", nullable=false)
	private byte roleId ;


	//--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="role_id", referencedColumnName="id", insertable=false, updatable=false)
	private Role       role ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
	private User       user ; 


	/**
	 * Constructor
	 */
	public UserRole() {
		super();
	}
	
	//--- GETTERS & SETTERS FOR FIELDS
	public void setId( int id ) {
		this.id = id ;
	}
	public int getId() {
		return this.id;
	}

	public void setUserId( int userId ) {
		this.userId = userId ;
	}
	public int getUserId() {
		return this.userId;
	}

	public void setRoleId( byte roleId ) {
		this.roleId = roleId ;
	}
	public byte getRoleId() {
		return this.roleId;
	}

	//--- GETTERS FOR LINKS
	public Role getRole() {
		return this.role;
	} 

	public User getUser() {
		return this.user;
	} 

	//--- toString specific method
	@Override
 public String toString() { 
  StringBuilder sb = new StringBuilder(); 
  sb.append(id);
  sb.append("|");
  sb.append(userId);
  sb.append("|");
  sb.append(roleId);
  return sb.toString(); 
 } 

}