export const STATUS = {
	WAITING: 'WAITING',
	ACCEPTED: 'ACCEPTED',
	REJECTED: 'REJECTED',
	CANCELED: 'CANCELED'
};

export const PERIOD = {
	CLOSE_APPOINTMENT: 'CLOSE_APPOINTMENT',
	CLOSE_EMPLOYEE_BREAK: 'CLOSE_EMPLOYEE_BREAK',
	CLOSE_PROVIDER_BREAK: 'CLOSE_PROVIDER_BREAK'
};